<?php
echo "<!doctype html>";
echo "<html lang=\"en\">";
echo "  <head>";
echo "    <meta charset=\"utf-8\">";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">";
echo "";
echo "    <title>File Drag and Drop</title>";
echo "";
echo "    <!-- Bootstrap core CSS -->";
echo "    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css\" integrity=\"sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy\" crossorigin=\"anonymous\">";
echo "";
echo "    <!-- Custom styles -->";
echo "    <link href=\"../dist/css/jquery.dm-uploader.min.css\" rel=\"stylesheet\">";
echo "    <link href=\"styles.css\" rel=\"stylesheet\">";
echo "  </head>";
echo "";
echo "  <body>";
echo "";
echo "    <main role=\"main\" class=\"container\">";
echo "";
echo "           <div class=\"row\">";
echo "        <div class=\"col-md-6 col-sm-12\">";
echo "            <!-- Our markup, the important part here! -->";
echo "          <div id=\"drag-and-drop-zone\" class=\"dm-uploader p-5\">";
echo "            <h3 class=\"mb-5 mt-5 text-muted\">Drag &amp; drop files here</h3>";
echo "";
echo "            <div class=\"btn btn-primary btn-block mb-5\">";
echo "                <span>Open the file Browser</span>";
echo "                <input type=\"file\" title=\'Click to add Files\' />";
echo "            </div>";
echo "          </div><!-- /uploader -->";
echo "";
echo "        </div>";
echo "        <div class=\"col-md-6 col-sm-12\">";
echo "          <div class=\"card h-100\">";
echo "            <div class=\"card-header\">";
echo "              File List";
echo "            </div>";
echo "";
echo "            <ul class=\"list-unstyled p-2 d-flex flex-column col\" id=\"files\">";
echo "              <li class=\"text-muted text-center empty\">No files uploaded.</li>";
echo "            </ul>";
echo "          </div>";
echo "        </div>";
echo "      </div><!-- /file list -->";
echo "";
echo "";
echo "      <div class=\"row\">";
echo "        <div class=\"col-12\">";
echo "           <div class=\"card h-100\">";
echo "            <div class=\"card-header\">";
echo "              Debug Messages";
echo "            </div>";
echo "";
echo "            <ul class=\"list-group list-group-flush\" id=\"debug\">";
echo "              <li class=\"list-group-item text-muted empty\">Loading plugin....</li>";
echo "            </ul>";
echo "          </div>";
echo "        </div>";
echo "      </div> <!-- /debug -->";
echo "";
echo "    </main> <!-- /container -->";
echo "";
echo "    <footer class=\"text-center\">";
echo "	<form action=\"rename.php\" method=\"post\">";
echo " <p>Enter Duration</p>";
echo "  Quantity (between 1 and 90):";
echo "  <input type=\"number\" name=\"quantity\" min=\"1\" max=\"90\"><br/>";
echo "Enter file name: <input type=\"text\" name=\"fileName\"><br>";
echo "<p id=\"countdown\"></p>";
echo "<input value=\"Save File\" type=\"submit\">";
echo "</form>";
echo "	    </footer>";
echo "";
echo "    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\" integrity=\"sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=\" crossorigin=\"anonymous\"></script>";
echo "    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js\" integrity=\"sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4\" crossorigin=\"anonymous\"></script>";
echo "";
echo "    <script src=\"../dist/js/jquery.dm-uploader.min.js\"></script>";
echo "    <script src=\"demo-ui.js\"></script>";
echo "    <script src=\"demo-config.js\"></script>";
echo "";
echo "    <!-- File item template -->";
echo "    <script type=\"text/html\" id=\"files-template\">";
echo "      <li class=\"media\">";
echo "        <div class=\"media-body mb-1\">";
echo "          <p class=\"mb-2\">";
echo "            <strong>%%filename%%</strong> - Status: <span class=\"text-muted\">Waiting</span>";
echo "          </p>";
echo "          <div class=\"progress mb-2\">";
echo "            <div class=\"progress-bar progress-bar-striped progress-bar-animated bg-primary\"";
echo "              role=\"progressbar\"";
echo "              style=\"width: 0%\"";
echo "              aria-valuenow=\"0\" aria-valuemin=\"0\" aria-valuemax=\"100\">";
echo "            </div>";
echo "          </div>";
echo "          <hr class=\"mt-1 mb-1\" />";
echo "        </div>";
echo "      </li>";
echo "    </script>";
echo "";
echo "    <!-- Debug item template -->";
echo "    <script type=\"text/html\" id=\"debug-template\">";
echo "      <li class=\"list-group-item text-%%color%%\"><strong>%%date%%</strong>: %%message%%</li>";
echo "    </script>";
echo "  </body>";
echo "</html>";
echo "";
?>