<?php
echo "";
echo "";
echo "";
echo "<!DOCTYPE html>";
echo "<html>";
echo "<head>";
echo "";
echo "";
echo "";
echo "</head>";
echo "";
echo "<style>";
echo "img";
echo "{";
echo "    display: block;";
echo "    margin-left: auto;";
echo "    margin-right: auto;";
echo "	width: 100vw;";
echo "	<!-- height: 100vh; -->";
echo "}";
echo "";
echo "</style>";
echo "";
echo "";
echo "";
echo "<body bgcolor=\"#aaaaaa\">";
echo "";
echo "<img id=\"cat\" src=\"Test Images/small-kitten-meowing.jpg\">";
echo "";
echo "<p id=\"printhere\"></p>";
echo "";
echo "<!-- GIF Image";
echo "<img id=\"cat-gif\" src=\"Test Images/cat-gif.gif\">";
echo "-->";
echo "";
echo "";
echo "<input type=\"file\" id=\"openFile\" />";
echo "<br>";
echo "<pre id=\"fileContents\"></pre>";
echo "";
echo "";
echo "";
echo "<!--";
echo "TODO:";
echo "- Scale Image (To minimum side length)";
echo "X Center Image";
echo "X Set Background to Black";
echo "- Dynamically retrieve list";
echo "-->";
echo "";
echo "<!--";
echo "stuff:";
echo "- Use PHP to get the image hieght / width";
echo "- Use PHP to get the screen hieght / width";
echo "- divide and multiply to see if the image can reach the screen height / width";
echo "- If the image height * 1.25 = screen hieght but image width * 1.15 = screen width use 1.15 for both";
echo "";
echo "-->";
echo "";
echo "";
echo "";
echo "";
echo "</body>";
echo "";
echo "<script>";
echo "";
echo "";
echo "// TODO:";
echo "// Read from text file to get list of files and their durations";
echo "// Get screen resolution";
echo "// Resize image appropriatly";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "// Read in from text file 1";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "// Read in from text file 2";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "/*";
echo "";
echo "var fs = require(\"fs\");";
echo "";
echo "";
echo "var fileList = [0];";
echo "var durationList = [0];";
echo "";
echo "";
echo "window.onload = function() {changeImage()};";
echo "";
echo "// Is this code running?";
echo "fs.readFile(\"Test Image/slides.txt\", function(text)";
echo "{";
echo "    var line = text.split(\"\\n\");";
echo "";
echo "	// Test";
echo "	document.getElementById(\"printhere\").innerHTML = \"printing: \" + line;";
echo "";
echo "";
echo "	var result = line[0].toString.split(\":\");";
echo "	var temp = result[0].toString.split(\".\");";
echo "	var ext = temp[1];";
echo "";
echo "";
echo "	if(!(ext == \".txt\")";
echo "	{";
echo "		filename = \"Test Images/\" + result[0];";
echo "		duration = result[1];";
echo "	}";
echo "";
echo "	fileList.unshift(filename);";
echo "	durationList.unshift(duration);";
echo "";
echo "";
echo "});";
echo "";
echo "*/";
echo "";
echo "// Not Reached";
echo "var printthis = \"Hello\";";
echo "";
echo "// Test";
echo "	document.getElementById(\"printhere\").innerHTML = \"printing: \" + printthis;";
echo "";
echo "";
echo "";
echo "";
echo "var fileList = [";
echo "    \"Test Images/black-cat.jpg\",";
echo "    \"Test Images/cat-jump.jpg\",";
echo "    \"Test Images/small-kitten-meowing.jpg\",";
echo "	\"Test Images/cat-gif.gif\"";
echo "];";
echo "";
echo "var durationList = [";
echo "    3,";
echo "	4,";
echo "	5,";
echo "	2";
echo "];";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "var index = 0;";
echo "";
echo "";
echo "";
echo "function changeImage()";
echo "{";
echo "    index = index + 1;";
echo "    if (index == fileList.length) index = 0;";
echo "    var image = document.getElementById('cat');";
echo "	printthis = fileList[index];";
echo "    image.src = fileList[index];";
echo "";
echo "	// Test";
echo "	document.getElementById(\"printhere\").innerHTML = \"duration: \" + printthis;";
echo "";
echo "";
echo "}";
echo "setInterval(function(){changeImage()}, durationList[index] * 1000);";
echo "";
echo "";
echo "";
echo "";
echo "";
echo "document.head.appendChild(x);";
echo "</script>";
echo "";
echo "</html>";
echo "";
?>