<?php
echo "<!DOCTYPE html>";
echo "<html>";
echo "<head>";
echo "<meta charset=\"UTF-8\">";
echo "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">";
echo "<title>Chattanooga1 Facility</title>";
echo "<link href=\"css/mainpage.css\" rel=\"stylesheet\">";
echo "</head>";
echo "<body>";
echo "<nav class=\"navbar navbar-default\">";
echo "  <div class=\"container-fluid\">";
echo "    <div class=\"navbar-header\">";
echo "      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#defaultNavbar1\">Toggle navigation</button>";
echo "      <a class=\"navbar-brand\" href=\"https://www.woodbridgegroup.com/\">The WoodBridge Group</a></div>";
echo "    <div class=\"collapse navbar-collapse\" id=\"defaultNavbar1\">";
echo "      <ul class=\"nav navbar-nav\">";
echo "        <li><a href=\"#\">About</a></li>";
echo "        <li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">Countries</a>";
echo "          <ul class=\"dropdown-menu\" role=\"menu\">";
echo "            <li><a href=\"#\">Action</a></li>";
echo "            <li><a href=\"#\">Another action</a></li>";
echo "            <li><a href=\"#\">Something else here</a></li>";
echo "            <li class=\"divider\"></li>";
echo "            <li><a href=\"#\">Separated link</a></li>";
echo "            <li class=\"divider\"></li>";
echo "            <li><a href=\"#\">One more separated link</a></li>";
echo "          </ul>";
echo "        </li>";
echo "      </ul>";
echo "      <form class=\"navbar-form navbar-left\" role=\"search\">";
echo "        <div class=\"form-group\">";
echo "          <input type=\"text\" class=\"form-control\" placeholder=\"Search\">";
echo "        </div>";
echo "        <button type=\"submit\" class=\"btn btn-default\">Submit</button>";
echo "      </form>";
echo "      <ul class=\"nav navbar-nav navbar-right\">";
echo "        <li></li>";
echo "        <li><a href=\"#\">Login</a>";
echo "          <ul class=\"dropdown-menu\" role=\"menu\">";
echo "            <li><a href=\"#\">Action</a></li>";
echo "            <li><a href=\"#\">Another action</a></li>";
echo "            <li><a href=\"#\">Something else here</a></li>";
echo "            <li class=\"divider\"></li>";
echo "            <li><a href=\"#\">Separated link</a></li>";
echo "          </ul>";
echo "        </li>";
echo "      </ul>";
echo "    </div>";
echo "  </div>";
echo "</nav>";
echo "<div class=\"container-fluid\">";
echo "  <div class=\"row\">";
echo "    <div class=\"col-md-6 col-md-offset-3\"> </div>";
echo "	  <img src=\"img/monitorhub.jpg\" width=\"600\" height=\"400\" style=\"display: block; margin-left: auto; margin-right: auto\"/>";
echo "  </div>";
echo "</div>";
echo "<br>";
echo "<br>";
echo "<div class=\"container\">";
echo "  <div class=\"row\">";
echo "    <div class=\"text-center col-md-6 col-md-offset-3\">";
echo "      <p>Copyright &copy; 2015 &middot; All Rights Reserved &middot; <a href=\"https://www.woodbridgegroup.com/\" >TheWoodBridgeGroup</a></p>";
echo "    </div>";
echo "  </div>";
echo "</div>";
echo "</body>";
echo "</html>";
echo "";
?>